### ISSUE TITLE
cawbird is dumping all API responses to the system log in plaintext

### ISSUE THREAD

**Issue by mind74** [diddlesnaps/cawbird#6] opened 2021-01-08 20:39 UTC
hi, according to cawbird developer, this issue apparently only affects flatpack and snap builds
sorry for my english :)

**Comment by philipzae** [comment] 2021-01-10 08:51
"We've been made aware of a problem with the Flatpak builds that results in them dumping all API responses (including the content of DMs) to the system log in plaintext.

This is not a bug in Cawbird, but is a result of debugging functionality being enabled in packaged builds." [Cawbird Twitter](https://twitter.com/CawbirdClient/status/1347623598383501312)

Presume if debug isn't enabled in the snap, the snap wouldn't be having this problem.

**Comment by diddledan** [comment] 2021-01-10 22:38
Thanks for reporting.

Fixed with 33dba53

**Closed by diddledan** 2021-01-10 22:38 UTC
